# 图数据库类型
graphType: galaxybase
# 图名称
graphName: Twitter-2010
# 默认样本文件
sample: sample/Twitter-2010-kn-sample.txt
samples:
  #最短路径样本名称
  sp: sample/Twitter-2010-sp-sample.txt
# 超时时间,单位：s
timeout: 3600
# 遇到错误时跳过测试项
timeoutStop: false
# 遇到错误时跳过测试项
errorStop: true
# 数据库所在包名
dataBaseClass: com.galaxybase.benchmark.galaxybase.developer.database.GalaxyData
# 自定义参数
parameters:
  vertexType: person
  edgeType: know
  ip: localhost
  port: 7687
  user: admin
  password: admin
  prop: false
test:
  #K-neighbor 1度查询
  - testClass: com.galaxybase.benchmark.galaxybase.developer.item.KNeighbor1
    count: 300
    loop: 3
    timeout: 180
  #K-neighbor 2度查询
  - testClass: com.galaxybase.benchmark.galaxybase.developer.item.KNeighbor2
    count: 300
    loop: 3
    timeout: 180
  #K-neighbor 3度查询
  - testClass: com.galaxybase.benchmark.galaxybase.developer.item.KNeighbor3
    count: 10
    loop: 3
  #K-neighbor 4度查询
  - testClass: com.galaxybase.benchmark.galaxybase.developer.item.KNeighbor4
    count: 10
    loop: 3
  #K-neighbor 5度查询
  - testClass: com.galaxybase.benchmark.galaxybase.developer.item.KNeighbor5
    count: 10
    loop: 3
  #K-neighbor 6度查询
  - testClass: com.galaxybase.benchmark.galaxybase.developer.item.KNeighbor6
    count: 10
    loop: 3

  #### 算法部分
  ###PageRank算法测试
  - testClass: com.galaxybase.benchmark.galaxybase.developer.item.PageRank
    count: 1
    loop: 3
  #Weak Connected Component算法测试
  - testClass: com.galaxybase.benchmark.galaxybase.developer.item.WeaklyConnectedComponents
    count: 1
    loop: 3
  #Label Propagation Algorithm算法测试
  - testClass: com.galaxybase.benchmark.galaxybase.developer.item.LabelPropagation
    count: 1
    loop: 3
  #Degree Centrality算法测试
  - testClass: com.galaxybase.benchmark.galaxybase.developer.item.DegreeCentrality
    count: 1
    loop: 3
  #Shortest Path算法测试
  - testClass: com.galaxybase.benchmark.galaxybase.developer.item.ShortestPath
    count: 100
    loop: 3
    sample: sp
